# Assigment 1
## Chapter 1 & Chapter 2

#### Due Date: 11 Disember 2023

Instructions:

    1. This is a group assignment. Each groups shall have **AT MOST** 3 students.
    2. Only one submission per group.
    3. The file to submit is in ipynb format (not py).
    4. Please put all members' full name and matric number.
    5. The assignment should be submitted by 11.59pm of the due date.

## Group Members



```
1.MUHAMMAD HARITH HAKIM BIN OTHMAN A21EC0205
2.MUHAMMAD AMIR JAMIL BIN JAMLUS A21EC0202
3.FU WANQIAN X23EC0004
4.IZZAT HAQEEMI BIN HAIRUDIN A21EC0033
```

## Only use Python Basics for this assignment.
## Do not import any other libraries or packages.

### Question 1

Create a function name verbing which receive a string as the parameter. Upon receiving a string:
- if its length is at least 3: add 'ing' to its end.
- Unless it already ends in 'ing', in which case add 'ly' instead.
- If the string length is less than 3, leave it unchanged.
- Return the resulting string.

Test your code with these strings. You should get the outputs as follow:

    String	          Expected Output
    Hail	             Hailing
    Swimming	     Swimmingly
    Do	                Do

In [ ]:
#Write your code here
def My_String(a):
    if len(a)>=3:
        if 'ing' not in a:
            a=a+"ing"
        else: a=a+"ly"
    return a

a='swimming'
My_String(a)

'swimmingly'

### Question 2

Convert the following code to list comprehension.

	cords = [ ]
	for x in range(4):
    	for y in range(2):
        	coordinate = (x, y)
        	cords.append(coordinate)
	print(cords)

In [ ]:
#Write your code here

cords=[(x,y) for x in range(4) for y in range(2)]
print(cords)

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1), (3, 0), (3, 1)]

### Question 3

Given an input list [34, 54, 67, 89, 11, 43, 94], use ```pop```, ```insert``` and ```append``` methods to
- remove the element at index 4
- add it to the 2nd position and at the end of the list


Expected output:

    Original list  [34, 54, 67, 89, 11, 43, 94]
    List after removing element at index 4  [34, 54, 67, 89, 43, 94]
    List after Adding element at index 2  [34, 54, 11, 67, 89, 43, 94]
    List after Adding element at last  [34, 54, 11, 67, 89, 43, 94, 11]

In [ ]:
#Write your code here
original_list = [34, 54, 67, 89, 11, 43, 94]
print("Original list  ", original_list)

removed_element = original_list.pop(4)
print("List after removing element at index 4  ", original_list)

original_list.insert(2, removed_element)
print("List after adding element at index 2  ", original_list)

original_list.append(removed_element)
print("List after adding element at last  ", original_list)

Original list   [34, 54, 67, 89, 11, 43, 94]
List after removing element at index 4   [34, 54, 67, 89, 43, 94]
List after adding element at index 2   [34, 54, 11, 67, 89, 43, 94]
List after adding element at last   [34, 54, 11, 67, 89, 43, 94, 11]

### Question 4

Create a function named ``calculate_result`` which receive any values and perform these tasks:

(i) If the value given is a valid input (0-100), the function returns these parameters:<br>
        ``marks``: the value sent to the function <br>
        ``status``: either 'PASS' for marks greater or equal to 40 or 'FAIL' for marks less than 40 <br>
        ``grade``: grade given according to the marks <br>
        ``point``: point given according to the marks

(ii) If the value given is an invalid input which is out of the range, an error message "The marks is out of range" should be displayed.

Figure 1 shows the grade and point allocated according to the marks.

<br>
<img src="Figure 1.png", style="width: 550px";>
<p style="text-align: center;">Figure 1</p>



Your output should look like Figure 2 below.

<br>
<img src="Figure 2a.png", style="width: 550px";>
<p style="text-align: center;">Figure 2</p>

In [ ]:
def calculated_result(m):
    if 0 <= m <= 100:
        if m >= 40:
            status = 'PASS'
        else:
            status = 'FAIL'

        if 90 <= m:
            grade = 'A+'
            point = 4.00
        elif 80 <= m:
            grade = 'A'
            point = 4.00
        elif 75 <= m:
            grade = 'A-'
            point = 3.67
        elif 70 <= m:
            grade = 'B+'
            point = 3.33
        elif 65 <= m:
            grade = 'B'
            point = 3.00
        elif 60 <= m:
            grade = 'B-'
            point = 2.67
        elif 55 <= m:
            grade = 'C+'
            point = 2.33
        elif 50 <= m:
            grade = 'C'
            point = 2.00
        elif 45 <= m:
            grade = 'C-'
            point = 1.67
        elif 40 <= m:
            grade = 'D+'
            point = 1.33
        else:
            grade = 'E'
            point = 0.00

        print("Your marks is: ", m)
        print("Your status is ", status, "with the grade of ", grade, "and point received is ", point)
    else:
        print("The marks are out of range")

# Test
calculated_result(71)

Your marks is:  71
Your status is  PASS with the grade of  B+ and point received is  3.33

### Question 5

Given a paragraph as follows:

On most computer systems, localhost resolves to the IP address 10.100.11.121, which is the most commonly used IPv4 loopback address, and to the IPv6 loopback address. The localhost IP address is 192.168.11.10.

Using regular expression, write the python code that can find the network IP address and replace it to 179.01.10.1.

In [ ]:
#Write your code here

#using re.sub
import re

# IP Address
IPAddress= " IP address is 10.100.11.121 meanwhile the localhost IP address is 192.168.11.10."
NewIP = " IP address is 10.100.11.121 meanwhile the localhost IP address is 192.168.11.10. "

# Regular expression pattern to match an IPv4 address
ipv4_pattern = r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'

# Replace the IP address with "179.01.10.1"
updated_IP = re.sub(ipv4_pattern, "179.01.10.1", NewIP)

print (IPAddress)
print(updated_IP)

 IP address is 10.100.11.121 meanwhile the localhost IP address is 192.168.11.10.
 IP address is 179.01.10.1 meanwhile the localhost IP address is 179.01.10.1.

### Question 6

A list of names in the format "first_name last_name" is given. Your task is to sort the list of names based on the last name in ascending order. Write a function called `sort_names_by_last_name` that takes in a list of names as input and uses a lambda function along with the ``sorted()`` function to solve the problem.

Example:<br>
If the input list is <br> `['John Smith', 'Alice Johnson', 'Michael Brown', 'Emily Davis']`, <br> the function should return <br> `['Michael Brown', 'Emily Davis', 'Alice Johnson', 'John Smith']`.

In [ ]:
#Write your code here

def sort_name_by_last_name(names):

  sort_name = sorted(names, key = lambda x : x.split()[-1])
  return sort_name

input_names = ['John Smith', 'Alice Johnson', 'Michael Brown', 'Emily Davis']
sort_name = sort_name_by_last_name(input_names)
print(sort_name)

['Michael Brown', 'Emily Davis', 'Alice Johnson', 'John Smith']

### Question 7

A list of strings is given. Write a function called `string_lengths_dict` that takes in a list of strings as input and returns the dictionary using dictionary comprehension. The dictionary that will be created should have the keys which are the strings from the list, and the corresponding values are the lengths of the strings.

Example:<br>
If the input list is <br> `['apple', 'banana', 'cherry', 'date']`,<br> the function should return <br>`{'apple': 5, 'banana': 6, 'cherry': 6, 'date': 4}`.

In [1]:
def string_lengths_dict():
    n = int(input("Enter the number of fruits: "))
    fruit_list = []
    FruitDict = {}

    for i in range(n):
        fruit = input("Enter a fruit: ")
        fruit_list.append(fruit)

    print("List of fruits:", fruit_list)

    for i in range (n):
      FruitDict[fruit_list[i]] = len(fruit_list[i])

    print("The Key and Value are: " , FruitDict)

string_lengths_dict()

Enter the number of fruits: 2
Enter a fruit: kiwi
Enter a fruit: apple
List of fruits: ['kiwi', 'apple']
The Key and Value are:  {'kiwi': 4, 'apple': 5}

### Question 8

Given a data file (Data_1.txt) that consists of an example daily sale information recorded manually for each of the transaction for a certain period. The information in the file consists of date, item name, amount sold, and price per unit.

<br>
<img src='Fig1.png' width='300px'>
The sample of the data

**INSTRUCTIONS:**
1. Reads the data file in Python.
2. Creates a function in Python called: **calculate_daily_sale** that:
   - Able to calculate and return the sale of each item for every day.
   - You need to determine the data structure for the returned information, where the returned result should be able to be accessed to show the sale of exact item on a specified day. E.g.:
      - ```result[“2020-09-25”]``` *will returns the sale for each item on that day.*
      - ```result[“2020-09-25”][“Item_B”]``` *will returns the sale of Item B on that day.*
3. Creates a function in Python called: **get_total_sale** that:
   - Able to combine the sale of a specific item throughout the period in the data file.
   - The function should receive ONE argument:
     - The result variable returned form **calculate_daily_sale**
   - The function should return the total sale of each item throughout the period.

In [ ]:
from google.colab import files
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
column_names = ["Date", "Item", "Quantity", "Price"]
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATASET/Data_1.txt', sep=' ', names=column_names)
df

          Date    Item  Quantity  Price
0   2020-09-23  Item_A         5    1.9
1   2020-09-23  Item_B         6    1.2
2   2020-09-23  Item_A         2    1.9
3   2020-09-23  Item_B         3    1.2
4   2020-09-24  Item_A        13    1.9
5   2020-09-24  Item_B         2    1.2
6   2020-09-24  Item_C         8    1.3
7   2020-09-25  Item_D         7    2.7
8   2020-09-25  Item_A        15    1.9
9   2020-09-25  Item_D         7    2.7
10  2020-09-25  Item_B         6    1.2
11  2020-09-26  Item_B         1    1.2
12  2020-09-26  Item_C         8    1.3
13  2020-09-26  Item_B        11    1.2
14  2020-09-26  Item_A         5    1.9
15  2020-09-26  Item_B         2    1.2
16  2020-09-26  Item_B        12    1.2
17  2020-09-26  Item_A         4    1.9
18  2020-09-26  Item_B         7    1.2
19  2020-09-27  Item_E         2    2.2
20  2020-09-27  Item_A         2    1.9
21  2020-09-27  Item_B         3    1.2
22  2020-09-27  Item_C        12    1.3
23  2020-09-27  Item_D        15    2.7
24  2020-09-28  Item_E         2    2.2
25  2020-09-28  Item_F         2    3.2
26  2020-09-28  Item_A         7    1.9
27  2020-09-28  Item_F         2    3.2
28  2020-09-28  Item_A         5    1.9
29  2020-09-28  Item_F         2    3.2
30  2020-09-28  Item_A         5    1.9
31  2020-09-28  Item_B         6    1.2
32  2020-09-28  Item_C        11    1.3
33  2020-09-28  Item_D        11    2.7
34  2020-09-29  Item_A         5    1.9
35  2020-09-29  Item_B         4    1.2
36  2020-09-29  Item_A         5    1.9
37  2020-09-29  Item_B         5    1.2
38  2020-09-29  Item_A         5    1.9
39  2020-09-29  Item_B         6    1.2
40  2020-09-30  Item_A         6    1.9
41  2020-09-30  Item_B         6    1.2
42  2020-09-30  Item_C         7    1.3
43  2020-09-30  Item_D         2    2.7
44  2020-09-30  Item_C         8    1.3
45  2020-09-30  Item_D         8    2.7
46  2020-09-30  Item_C         9    1.3
47  2020-09-30  Item_D         7    2.7
48  2020-09-30  Item_E         2    2.2
49  2020-09-30  Item_F         2    3.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Item      50 non-null     object
 2   Quantity  50 non-null     int64
 3   Price     50 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.7+ KB

In [ ]:
def calculate_daily_sale(dataframe):

    daily_sales = {}


    for index, row in dataframe.iterrows():
        date = row['Date']
        item = row['Item']
        quantity = row['Quantity']
        price = row['Price']
        daily_sale = quantity * price


        if date not in daily_sales:
            daily_sales[date] = {}


        if item not in daily_sales[date]:
            daily_sales[date][item] = 0

        daily_sales[date][item] += daily_sale

    return daily_sales


result = calculate_daily_sale(df)


print(result["2020-09-25"])
print(result["2020-09-25"]["Item_B"])

{'Item_D': 37.800000000000004, 'Item_A': 28.5, 'Item_B': 7.199999999999999}
7.199999999999999

In [ ]:
def get_total_sale(daily_sales):
    total_sales = {}

    for date, items in daily_sales.items():
        for item, sale in items.items():
            if item not in total_sales:
                total_sales[item] = 0
            total_sales[item] += sale

    return total_sales


result = calculate_daily_sale(df)

total_sales = get_total_sale(result)

print("Total Sales For Item_A is :" ,total_sales["Item_A"])
print("Total Sales For Item_B is :" ,total_sales["Item_B"])
print("Total Sales For Item_C is :" ,total_sales["Item_C"])
print("Total Sales For Item_D is :" ,total_sales["Item_D"])
print("Total Sales For Item_E is :" ,total_sales["Item_E"])
print("Total Sales For Item_F is :" ,total_sales["Item_F"])

Total Sales For Item_A is : 159.6
Total Sales For Item_B is : 96.0
Total Sales For Item_C is : 81.9
Total Sales For Item_D is : 153.90000000000003
Total Sales For Item_E is : 13.200000000000001
Total Sales For Item_F is : 25.6