# ASSIGNMENT 2
**Topic: Chapter 3 & Chapter 4**
- Due: 4th December 2023
- Mode: Group Assignment (Not more than 3 students per group)
- Submission: E-Learning

## Group Members



```
1.MUHAMMAD HARITH HAKIM BIN OTHMAN A21EC0205
2.MUHAMMAD AMIR JAMIL BIN JAMLUS A21EC0202
3.FU WANQIAN X23EC0004
4.IZZAT HAQEEMI BIN HAIRUDIN A21EC0033
```

### QUESTION 1


Given a raw data of the record of the attendance for 15 employees in a company for a 14 days event. The exported raw data is recorded in following way:

<br>
<center>Figure 1</center>
<img src="Figure 1.png", style="width: 350px";>

(i) Read the “Attendance_RAW.txt” and save the data into a NumPy array.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [11]:
# WRITE YOUR CODE HERE
# WRITE YOUR CODE HERE
import numpy as np
data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/DATASET/Attendance_RAW.txt', delimiter=',')
data

<ipython-input-11-c3f323b632f6>:4: UserWarning: genfromtxt: Empty input file: "/content/drive/MyDrive/Colab Notebooks/DATASET/Attendance_RAW.txt"
  data = np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/DATASET/Attendance_RAW.txt', delimiter=',')

array([], dtype=float64)

(ii) Shape the NumPy array to a structure where row represents the employees, column represents the working days.

In [ ]:

# WRITE YOUR CODE HERE
n = 15
m = 14
reshaped_data = data.reshape(n, m)
reshaped_data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1.],
       [1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1.]])

(iii) Construct a function that can calculate and return the list of average of attendance for each day.

In [ ]:
# WRITE YOUR CODE HERE
def get_average_attendance(data):
    return np.mean(data, axis=0)

get_average_attendance(reshaped_data)

array([0.6       , 0.6       , 0.73333333, 0.8       , 0.73333333,
       0.8       , 0.86666667, 0.86666667, 0.73333333, 0.73333333,
       0.73333333, 0.73333333, 0.8       , 0.8       ])

### QUESTION 2

(i) Create a NumPy array like below:

<br>
<img src="Output2.png", style="width: 200px", align="left";>

In [ ]:
# WRITE YOUR CODE HERE
import numpy as np
data=[[33,22,11],[55,66,44],[99,88,77]]
arr=np.array(data)
arr

array([[33, 22, 11],
       [55, 66, 44],
       [99, 88, 77]])

(ii) Sort the array given in ascending order.

In [ ]:
# WRITE YOUR CODE HERE
arr=np.sort(arr)
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

(iii) Compute sum of all elements, sum of each column and sum of each row of the sorted array.

In [ ]:
# WRITE YOUR CODE HERE
print(np.sum(arr))
print(arr.sum(axis=0))##column
print(arr.sum(axis=1)) ##row

495
[132 165 198]
[ 66 165 264]

(iv) Compute mean of all elements, mean of each column and mean of each row of the sorted array.

In [ ]:
# WRITE YOUR CODE HERE
print(np.mean(arr))
print(arr.mean(axis=0))##column
print(arr.mean(axis=1)) ##row

55.0
[44. 55. 66.]
[22. 55. 88.]

(v) Compute cumulative sum of each column and cumulative product of each row of the given array.

In [ ]:
# WRITE YOUR CODE HERE
print(arr.cumsum(axis=0))
print(arr.cumprod(axis=1))

[[ 11  22  33]
 [ 55  77  99]
 [132 165 198]]
[[    11    242   7986]
 [    44   2420 159720]
 [    77   6776 670824]]

### QUESTION 3
For this question, you are using Automobile Dataset.

(i) Load the dataset into pandas dataframe.

In [1]:
# WRITE YOUR CODE HERE
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

(ii) Display the first and last 5 rows.

In [2]:
# WRITE YOUR CODE HERE (for the first 5 rows)
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATASET/Automobile Dataset.csv')
df.head(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [3]:
# WRITE YOUR CODE HERE (for the last 5 rows)
df.tail(5)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

(iii) Print most expensive car’s company name and price.

In [9]:
# WRITE YOUR CODE HERE

most_expensive_car = df.loc[df['price'].idxmax()]
print(f"Most expensive car: Company - {most_expensive_car['company']}, Price - ${most_expensive_car['price']}")

Most expensive car: Company - mercedes-benz, Price - $45400.0

(iv) Count total cars per company.

In [ ]:
# WRITE YOUR CODE HERE
car_counts = df['company'].value_counts()

print(car_counts)

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

(v) Select only Toyota's cars. Find the average mileage and price of Toyota's cars.

In [ ]:
# WRITE YOUR CODE HERE
toyota_cars = df[df["company"] == "toyota"]
avg_mileage = toyota_cars["average-mileage"].mean()
avg_price = toyota_cars["price"].mean()

print("Average mileage of Toyota cars is:", avg_mileage.round(2))
print("Average price of Toyota cars is:", avg_price.round(2))

Average mileage of Toyota cars is: 28.71
Average price of Toyota cars is: 8216.86

(vi) Sort all cars by Price and Horsepower column. List the expensive cars first.

In [ ]:
# WRITE YOUR CODE HERE
sort = df.sort_values(by=["price", "horsepower"], ascending = [False,False])
sort

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
...,...,...,...,...,...,...,...,...,...,...
27,36,mazda,hatchback,93.1,159.1,ohc,four,68,30,5195.0
13,16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151.0
47,63,porsche,hatchback,98.4,175.7,dohcv,eight,288,17,NaN
22,31,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN
23,32,isuzu,sedan,94.5,155.9,ohc,four,70,38,NaN

(vii) Display all the maximum car price for each company.

In [ ]:
# WRITE YOUR CODE HERE
car_brand = df['company'].unique()

for brand in car_brand:
  max_price = df[df['company'] == brand]['price'].max()
  print(f"Highest price of car for {brand}: {max_price}")

Highest price of car for alfa-romero: 16500.0
Highest price of car for audi: 18920.0
Highest price of car for bmw: 41315.0
Highest price of car for chevrolet: 6575.0
Highest price of car for dodge: 6377.0
Highest price of car for honda: 12945.0
Highest price of car for isuzu: 6785.0
Highest price of car for jaguar: 36000.0
Highest price of car for mazda: 18344.0
Highest price of car for mercedes-benz: 45400.0
Highest price of car for mitsubishi: 8189.0
Highest price of car for nissan: 13499.0
Highest price of car for porsche: 37028.0
Highest price of car for toyota: 15750.0
Highest price of car for volkswagen: 9995.0
Highest price of car for volvo: 13415.0

### QUESTION 4


Given a data file, “emp_detail.csv” which consists of the employee’s details - name and department.

<br>
<img src="Figure 2.png", style="width: 250px";>

(i) Using Pandas library, read the CSV data file in Python into a variable ``emp_detail``.

In [ ]:
# WRITE YOUR CODE HERE
import pandas as pd
emp_detail = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATASET/emp_detail.csv')
emp_detail

       Name Department
0       ALI    FINANCE
1     AHMAD   STAFFING
2     CHONG    FINANCE
3    DARREN   STAFFING
4   JASMINE   STAFFING
5    JOSHUA   STAFFING
6     KELLY    FINANCE
7       LIM    FINANCE
8   NATASHA    FINANCE
9      OMAR   STAFFING
10   PATRIC   STAFFING
11     ROSE   STAFFING
12    SATYA   STAFFING
13    TARIQ   STAFFING
14    USMAN   STAFFING

(ii) Display the first five rows of records of the data read in Step (i).

In [ ]:
# WRITE YOUR CODE HERE
emp_detail.head(5)

      Name Department
0      ALI    FINANCE
1    AHMAD   STAFFING
2    CHONG    FINANCE
3   DARREN   STAFFING
4  JASMINE   STAFFING

(iii) Using the NumPy object of the attendance record created earlier:<br>
            a.	Convert the NumPy object into Data Frame, name it attendance.<br>
            b.	Merge the Data Frames ``emp_detail`` and attendance into a new data frame, name it ``emp_attendance``.

In [ ]:
# WRITE YOUR CODE HERE
attendance = pd.DataFrame(reshaped_data)
attendance

     0    1    2    3    4    5    6    7    8    9    10   11   12   13
0   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1   0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0
2   1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0
3   1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
4   1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0
5   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0
6   1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0
7   0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0
8   0.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0
9   0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0
10  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
11  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0
12  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
13  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0
14  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0

In [ ]:
attendance = attendance.astype(int)
attendance

    0   1   2   3   4   5   6   7   8   9   10  11  12  13
0    1   1   1   1   1   1   1   1   1   1   1   1   1   1
1    0   1   1   1   1   1   1   1   1   1   0   1   1   1
2    1   1   1   1   1   1   0   1   0   0   1   1   0   1
3    1   0   1   1   0   1   1   1   1   0   1   1   1   1
4    1   0   0   0   1   1   1   1   0   0   0   0   1   1
5    1   1   1   1   1   1   1   1   0   1   1   1   0   1
6    1   1   1   0   0   1   1   1   0   1   1   0   1   1
7    0   0   1   1   1   1   1   1   1   1   0   0   1   0
8    0   1   1   1   1   0   1   0   1   1   0   1   1   1
9    0   1   0   1   0   1   1   1   1   1   1   0   1   0
10   0   0   0   1   1   1   1   1   1   1   1   1   1   1
11   1   1   1   1   1   1   1   1   1   1   1   1   1   0
12   1   1   0   0   0   0   1   1   1   1   1   1   1   1
13   0   0   1   1   1   1   1   1   1   1   1   1   0   1
14   1   0   1   1   1   0   0   0   1   0   1   1   1   1

In [ ]:
emp_attendance = pd.concat([emp_detail, attendance], axis=1)
emp_attendance

       Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1  1   0   1   1   1
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   1   0   1
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1  0   1   1   1   1
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0  0   0   0   1   1
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0  1   1   1   0   1
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0  1   1   0   1   1
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1  1   0   0   1   0
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1  1   0   1   1   1
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1  1   1   0   1   0
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1  1   1   1   1   1
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   0
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1  1   1   1   1   1
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1  1   1   1   0   1
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1  0   1   1   1   1

In [ ]:
emp_attendance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        15 non-null     object
 1   Department  15 non-null     object
 2   0           15 non-null     int64
 3   1           15 non-null     int64
 4   2           15 non-null     int64
 5   3           15 non-null     int64
 6   4           15 non-null     int64
 7   5           15 non-null     int64
 8   6           15 non-null     int64
 9   7           15 non-null     int64
 10  8           15 non-null     int64
 11  9           15 non-null     int64
 12  10          15 non-null     int64
 13  11          15 non-null     int64
 14  12          15 non-null     int64
 15  13          15 non-null     int64
dtypes: int64(14), object(2)
memory usage: 2.0+ KB

(iv) Add a column with name ``total`` into the ``emp_attendance`` Data Frame that consists of the total no. of days the employee attended the event.

In [ ]:
# WRITE YOUR CODE HERE
emp_attendance['total'] = emp_attendance.iloc[:, 2:16].sum(axis=1)
emp_attendance

       Name Department  0  1  2  3  4  5  6  7  8  9  10  11  12  13  total
0       ALI    FINANCE  1  1  1  1  1  1  1  1  1  1   1   1   1   1     14
1     AHMAD   STAFFING  0  1  1  1  1  1  1  1  1  1   0   1   1   1     12
2     CHONG    FINANCE  1  1  1  1  1  1  0  1  0  0   1   1   0   1     10
3    DARREN   STAFFING  1  0  1  1  0  1  1  1  1  0   1   1   1   1     11
4   JASMINE   STAFFING  1  0  0  0  1  1  1  1  0  0   0   0   1   1      7
5    JOSHUA   STAFFING  1  1  1  1  1  1  1  1  0  1   1   1   0   1     12
6     KELLY    FINANCE  1  1  1  0  0  1  1  1  0  1   1   0   1   1     10
7       LIM    FINANCE  0  0  1  1  1  1  1  1  1  1   0   0   1   0      9
8   NATASHA    FINANCE  0  1  1  1  1  0  1  0  1  1   0   1   1   1     10
9      OMAR   STAFFING  0  1  0  1  0  1  1  1  1  1   1   0   1   0      9
10   PATRIC   STAFFING  0  0  0  1  1  1  1  1  1  1   1   1   1   1     11
11     ROSE   STAFFING  1  1  1  1  1  1  1  1  1  1   1   1   1   0     13
12    SATYA   STAFFING  1  1  0  0  0  0  1  1  1  1   1   1   1   1     10
13    TARIQ   STAFFING  0  0  1  1  1  1  1  1  1  1   1   1   0   1     11
14    USMAN   STAFFING  1  0  1  1  1  0  0  0  1  0   1   1   1   1      9

(v) Add a column with name ``rate`` into the ``emp_attendance`` Data Frame that consists of the attendance rate / percentage the employee throughout the 14 days.

In [ ]:
# WRITE YOUR CODE HERE
emp_attendance['rate'] = emp_attendance['total']/14
emp_attendance

,Name,Department,0,1,2,3,4,5,6,7,8,9,10,11,12,13,total,rate
0,ALI,FINANCE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,14,1.000000
1,AHMAD,STAFFING,0,1,1,1,1,1,1,1,1,1,0,1,1,1,12,0.857143
2,CHONG,FINANCE,1,1,1,1,1,1,0,1,0,0,1,1,0,1,10,0.714286
3,DARREN,STAFFING,1,0,1,1,0,1,1,1,1,0,1,1,1,1,11,0.785714
4,JASMINE,STAFFING,1,0,0,0,1,1,1,1,0,0,0,0,1,1,7,0.500000
5,JOSHUA,STAFFING,1,1,1,1,1,1,1,1,0,1,1,1,0,1,12,0.857143
6,KELLY,FINANCE,1,1,1,0,0,1,1,1,0,1,1,0,1,1,10,0.714286
7,LIM,FINANCE,0,0,1,1,1,1,1,1,1,1,0,0,1,0,9,0.642857
8,NATASHA,FINANCE,0,1,1,1,1,0,1,0,1,1,0,1,1,1,10,0.714286
9,OMAR,STAFFING,0,1,0,1,0,1,1,1,1,1,1,0,1,0,9,0.642857
10,PATRIC,STAFFING,0,0,0,1,1,1,1,1,1,1,1,1,1,1,11,0.785714
11,ROSE,STAFFING,1,1,1,1,1,1,1,1,1,1,1,1,1,0,13,0.928571
12,SATYA,STAFFING,1,1,0,0,0,0,1,1,1,1,1,1,1,1,10,0.714286
13,TARIQ,STAFFING,0,0,1,1,1,1,1,1,1,1,1,1,0,1,11,0.785714
14,USMAN,STAFFING,1,0,1,1,1,0,0,0,1,0,1,1,1,1,9,0.642857

(vi) Consider following rules in classify the attendance:<br>
        a.	Rate > 90% : Good <br>
        b.	60% < Rate < 90% : Moderate <br>
        c.	Rate < 60% : Bad <br>
    Based on the grouping rule above, get the status for each of the staff and save the status in a new column ``status`` in the Data Frame.

In [ ]:
# WRITE YOUR CODE HERE
# WRITE YOUR CODE HERE
emp_attendance['status'] = np.where(emp_attendance['rate'] >= 0.9, 'Good', np.where(emp_attendance['rate'] <= 0.6, 'Bad', 'Moderate'))
emp_attendance

,Name,Department,0,1,2,3,4,5,6,7,8,9,10,11,12,13,total,rate,status
0,ALI,FINANCE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,14,1.000000,Good
1,AHMAD,STAFFING,0,1,1,1,1,1,1,1,1,1,0,1,1,1,12,0.857143,Moderate
2,CHONG,FINANCE,1,1,1,1,1,1,0,1,0,0,1,1,0,1,10,0.714286,Moderate
3,DARREN,STAFFING,1,0,1,1,0,1,1,1,1,0,1,1,1,1,11,0.785714,Moderate
4,JASMINE,STAFFING,1,0,0,0,1,1,1,1,0,0,0,0,1,1,7,0.500000,Bad
5,JOSHUA,STAFFING,1,1,1,1,1,1,1,1,0,1,1,1,0,1,12,0.857143,Moderate
6,KELLY,FINANCE,1,1,1,0,0,1,1,1,0,1,1,0,1,1,10,0.714286,Moderate
7,LIM,FINANCE,0,0,1,1,1,1,1,1,1,1,0,0,1,0,9,0.642857,Moderate
8,NATASHA,FINANCE,0,1,1,1,1,0,1,0,1,1,0,1,1,1,10,0.714286,Moderate
9,OMAR,STAFFING,0,1,0,1,0,1,1,1,1,1,1,0,1,0,9,0.642857,Moderate
10,PATRIC,STAFFING,0,0,0,1,1,1,1,1,1,1,1,1,1,1,11,0.785714,Moderate
11,ROSE,STAFFING,1,1,1,1,1,1,1,1,1,1,1,1,1,0,13,0.928571,Good
12,SATYA,STAFFING,1,1,0,0,0,0,1,1,1,1,1,1,1,1,10,0.714286,Moderate
13,TARIQ,STAFFING,0,0,1,1,1,1,1,1,1,1,1,1,0,1,11,0.785714,Moderate
14,USMAN,STAFFING,1,0,1,1,1,0,0,0,1,0,1,1,1,1,9,0.642857,Moderate

(vii) Construct a function that returns the average attendance of all staff over the 14 days according to the department.

In [ ]:
# WRITE YOUR CODE HERE
def attendane_by_dep(emp_attendance):
    return emp_attendance.groupby('Department').mean(['rate'])

attendane_by_dep(emp_attendance)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,total,rate
Department,,,,,,,,,,,,,,,,
FINANCE,0.6,0.8,1.0,0.8,0.8,0.8,0.8,0.8,0.6,0.8,0.6,0.6,0.8,0.8,10.6,0.757143
STAFFING,0.6,0.5,0.6,0.8,0.7,0.8,0.9,0.9,0.8,0.7,0.8,0.8,0.8,0.8,10.5,0.750000